# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-02 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_id', models.IntegerField(blank=True)),
                ('defunct', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ep_job',
            },
        ),
    ]
