# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-03 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defunct', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_id', models.IntegerField(blank=True)),
                ('photo_date', models.DateTimeField(blank=True, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.EPCompany')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.EPStatus')),
                ('workflow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.EPWorkflow')),
            ],
            options={
                'db_table': 'ep_job',
            },
        ),
        migrations.CreateModel(
            name='EPTaskAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defunct', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('remarks', models.CharField(max_length=100)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.EPJob')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.EPTask')),
                ('work_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.EPAccount')),
            ],
            options={
                'db_table': 'ep_task_assignment',
            },
        ),
    ]
