# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-02 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eptask',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
