# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20161104_0337'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epjob',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='epjob',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='epjob',
            old_name='workflow_id',
            new_name='workflow',
        ),
        migrations.RenameField(
            model_name='eptaskassignment',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='eptaskassignment',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='eptaskassignment',
            old_name='work_id',
            new_name='work',
        ),
        migrations.AddField(
            model_name='epjob',
            name='assignments',
            field=models.ManyToManyField(through='job.EPTaskAssignment', to='account.EPAccount'),
        ),
    ]
