# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-01 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='epaccount',
            table='account',
        ),
    ]
