# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-02 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20161101_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='epaccount',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
