# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20161104_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epaccountcompany',
            name='position',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.EPPosition'),
        ),
    ]
