# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20161104_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epaccountcompany',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.EPPosition'),
        ),
    ]
