# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-02 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('account', '0003_epaccount_wechat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
