# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-02 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_epcompany'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='epaccount',
            table='ep_account',
        ),
        migrations.AlterModelTable(
            name='epcompany',
            table='ep_company',
        ),
    ]
