# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-02 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20161102_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPAccountCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.EPAccount')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.EPCompany')),
            ],
            options={
                'db_table': 'ep_account_company',
            },
        ),
        migrations.CreateModel(
            name='EPPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.EPCompany')),
            ],
            options={
                'db_table': 'ep_position',
            },
        ),
        migrations.AddField(
            model_name='epaccountcompany',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.EPPosition'),
        ),
    ]
