# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-02 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20161102_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='epaccountcompany',
            name='defunct',
            field=models.BooleanField(default=False),
        ),
    ]
